### ISSUE TITLE
Errors in pip install

### ISSUE THREAD

**Issue by RParedesPalacios** [deephealthproject/pyeddl#17]
I try it but got some errors in Mac

```
pip3 install pyeddl
Collecting pyeddl
  Using cached https://files.pythonhosted.org/packages/06/00/3ddd0b0574051d64afd108570e7d0a31f1a3d2d66d1a9ccec9922fd5df0a/pyeddl-0.3.0.tar.gz
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/site-packages (from pyeddl) (41.0.1)
Requirement already satisfied: pybind11 in /usr/local/lib/python3.7/site-packages (from pyeddl) (2.4.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/site-packages (from pyeddl) (1.17.4)
Building wheels for collected packages: pyeddl
  Building wheel for pyeddl (setup.py) ... error
  ERROR: Complete output from command /usr/local/opt/python/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/pw/h8y74yv52hj4yl3d1r2k_2ph0000gn/T/pip-install-955av_r0/pyeddl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/pw/h8y74yv52hj4yl3d1r2k_2ph0000gn/T/pip-wheel-08zoog4p --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.14-x86_64-3.7
  creating build/lib.macosx-10.14-x86_64-3.7/pyeddl
  copying pyeddl/version.py -> build/lib.macosx-10.14-x86_64-3.7/pyeddl
  copying pyeddl/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/pyeddl
  running build_ext
  building 'pyeddl._core' extension
  creating build/temp.macosx-10.14-x86_64-3.7
  creating build/temp.macosx-10.14-x86_64-3.7/src
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -Isrc -I/usr/local/include/python3.7m -I/Users/rparedes/Library/Python/3.7/include/python3.7m -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c src/_core.cpp -o build/temp.macosx-10.14-x86_64-3.7/src/_core.o -std=c++11 -fvisibility=hidden
  src/_core.cpp:2:10: fatal error: 'eddl/descriptors/tensor_descriptors.h' file not found
  #include <eddl/descriptors/tensor_descriptors.h>
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
  error: command 'clang' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pyeddl
  Running setup.py clean for pyeddl
Failed to build pyeddl
Installing collected packages: pyeddl
  Running setup.py install for pyeddl ... error
    ERROR: Complete output from command /usr/local/opt/python/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/pw/h8y74yv52hj4yl3d1r2k_2ph0000gn/T/pip-install-955av_r0/pyeddl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/pw/h8y74yv52hj4yl3d1r2k_2ph0000gn/T/pip-record-1g0i2j5u/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.14-x86_64-3.7
    creating build/lib.macosx-10.14-x86_64-3.7/pyeddl
    copying pyeddl/version.py -> build/lib.macosx-10.14-x86_64-3.7/pyeddl
    copying pyeddl/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/pyeddl
    running build_ext
    building 'pyeddl._core' extension
    creating build/temp.macosx-10.14-x86_64-3.7
    creating build/temp.macosx-10.14-x86_64-3.7/src
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -Isrc -I/usr/local/include/python3.7m -I/Users/rparedes/Library/Python/3.7/include/python3.7m -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c src/_core.cpp -o build/temp.macosx-10.14-x86_64-3.7/src/_core.o -std=c++11 -fvisibility=hidden
    src/_core.cpp:2:10: fatal error: 'eddl/descriptors/tensor_descriptors.h' file not found
    #include <eddl/descriptors/tensor_descriptors.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    error: command 'clang' failed with exit status 1
    ----------------------------------------
ERROR: Command "/usr/local/opt/python/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/pw/h8y74yv52hj4yl3d1r2k_2ph0000gn/T/pip-install-955av_r0/pyeddl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/pw/h8y74yv52hj4yl3d1r2k_2ph0000gn/T/pip-record-1g0i2j5u/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/pw/h8y74yv52hj4yl3d1r2k_2ph0000gn/T/pip-install-955av_r0/pyeddl/
```

**Comment by simleo** [comment]
Looks like it's not finding the EDDL includes. By default, they are expected in a standard location, such as `/usr/include` or `/usr/local/include`. If you installed EDDL in a non-standard path, you can specify that via the `EDDL_DIR` environment variable. For instance, if EDDL is installed in `/opt/eddl`:

```
export EDDL_DIR=/opt/eddl
pip3 install pyeddl
```

Then pyeddl will add `/opt/eddl/include` to the include search path and `/opt/eddl/lib` to the library search path.

**Comment by RParedesPalacios** [comment]
Ok done! thanks!

Now I can import pyeddl 

however when I try some of the examples it fails to import pyeddl core

>>> import pyeddl._core.eddl as eddl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pyeddl._core'
>>> import pyeddl._core.eddlT as eddlT
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pyeddl._core'

**Comment by simleo** [comment]
Are you trying to run the examples from the pyeddl distribution root? That could be a problem, since that directory contains a `pyeddl` subdirectory that does not have the `_core*` extension file in it (that's only present in the installation directory). Since local packages take precedence in the import sequence, that can break the import. If so, you can try moving to the example directory before running it, e.g.:

```
cd examples/NN/1_MNIST
python3 mnist_auto_encoder.py
```

**Comment by RParedesPalacios** [comment]
Well, thanks, but what I expected is to install pyeddl and run it in any place. Also I expected to install peddle without having the EDDL headers around. Perhaps it is my fault because I do not understand the mechanics. Something like keras.

**Comment by simleo** [comment]
Local packages always take precedence over installed ones. This is **not** pyeddl-specific, it's how the python import mechanism works in general. Any package will run into problems if it's masked by a package with the same name in the CWD. For instance, if you have numpy installed on your machine (tested this with numpy 1.18.1):

```
$ python3 -c 'from numpy.core import _multiarray_umath'  # OK
$ mkdir numpy
$ touch numpy/__init__.py  # now a local package takes precedence
$ python3 -c 'from numpy.core import _multiarray_umath'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy.core'
```

Regarding the need to have eddl installed in order to build pyeddl, that's simply a dependency. You can't expect to make something work if dependencies are not satisfied. That's also true of Keras. If you simply run 'pip install keras' and then try to import it, you get this:

```
$ python3 -c 'import keras'
Using TensorFlow backend.
Traceback (most recent call last):
[...]  # Exception traceback omitted
ModuleNotFoundError: No module named 'tensorflow'
```

I.e., the tensorflow dependency is missing. In pyeddl, we need the header files because we are compiling from source. On the other hand, EDDL itself must be compiled from source, since there is no binary distribution. At some point we could try to work together on binary distributions, but those would be platform-specific ofc. We need to carefully weigh pros and cons, since it's not a trivial matter.

**Comment by RParedesPalacios** [comment]
Well, I have tried several time in several computers something like pip install tensor flow or pytorch and everything went well.
